# Generated by Django 3.1.7 on 2021-09-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Donna'), ('O', 'Other')], max_length=1, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('private_phone', models.PositiveIntegerField(blank=True, null=True)),
                ('office_phone', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('address2', models.TextField(blank=True, max_length=200, null=True)),
                ('postal_box', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, choices=[('IT', 'Italiano'), ('DE', 'Tedesco'), ('FR', 'Francese'), ('EN', 'Inglese')], max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(choices=[('CHF', 'FRANCO'), ('EUR', 'EURO'), ('USD', 'DOLLARO')], max_length=3)),
                ('cost_center', models.CharField(blank=True, max_length=200, null=True)),
                ('added_by', models.CharField(max_length=50)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='explanation.donor')),
            ],
        ),
    ]
